# Generated by Django 5.2.9 on 2025-12-29 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_campaign_campaign_type_campaign_end_date_and_more'),
        ('tenants', '0004_datadeletionrequest_featureflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_id', models.UUIDField(blank=True, help_text='Reference to WhatsAppTemplate.id', null=True)),
                ('template_name', models.CharField(help_text='WhatsApp template name', max_length=255)),
                ('language_code', models.CharField(default='en_US', help_text='Template language code', max_length=10)),
                ('header_image_url', models.URLField(blank=True, help_text='Header image URL for template', max_length=2048)),
                ('body_params', models.JSONField(blank=True, default=list, help_text='Default body parameters for template')),
                ('button_params', models.JSONField(blank=True, default=list, help_text='Button parameters for template')),
                ('scheduled_time', models.DateTimeField(db_index=True, help_text='Exact time to send messages (UTC)')),
                ('job_hash', models.CharField(help_text='Hash for deduplication', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial_failure', 'Partial Failure'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed')),
                ('claimed_by', models.CharField(blank=True, help_text='Server ID that claimed this job', max_length=100)),
                ('claimed_at', models.DateTimeField(blank=True, help_text='When job was claimed', null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Number of retry attempts')),
                ('max_retries', models.PositiveSmallIntegerField(default=3, help_text='Maximum retry attempts')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, help_text='Next retry time', null=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=255)),
                ('total_recipients', models.PositiveIntegerField(default=0, help_text='Total number of recipients')),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Successfully sent count')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='Failed send count')),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Priority (1=highest, 10=lowest)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='Associated campaign (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduler_jobs', to='campaigns.campaign')),
                ('tenant', models.ForeignKey(help_text='Client this job belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_jobs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Scheduler Job',
                'verbose_name_plural': 'Scheduler Jobs',
                'db_table': 'scheduler_jobs',
                'ordering': ['scheduled_time', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='SchedulerJobRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_id', models.UUIDField(blank=True, help_text='Reference to messaging.Contact.id', null=True)),
                ('phone_number', models.CharField(help_text='Recipient phone number', max_length=20)),
                ('contact_name', models.CharField(blank=True, help_text='Contact name for reference', max_length=255)),
                ('custom_body_params', models.JSONField(blank=True, default=list, help_text='Custom body parameters for this recipient')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='WhatsApp message ID if sent', max_length=255)),
                ('error_code', models.CharField(blank=True, help_text='Error code if failed', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Number of retry attempts for this recipient')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When message was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(help_text='Parent scheduler job', on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='scheduler.schedulerjob')),
            ],
            options={
                'verbose_name': 'Scheduler Job Recipient',
                'verbose_name_plural': 'Scheduler Job Recipients',
                'db_table': 'scheduler_job_recipients',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='schedulerjob',
            index=models.Index(fields=['status', 'scheduled_time'], name='scheduler_j_status_cf6caa_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerjob',
            index=models.Index(fields=['tenant', 'scheduled_time'], name='scheduler_j_tenant__7807e9_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerjob',
            index=models.Index(fields=['status', 'next_retry_at'], name='scheduler_j_status_9cf226_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerjob',
            index=models.Index(fields=['status', 'claimed_by'], name='scheduler_j_status_57f121_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerjobrecipient',
            index=models.Index(fields=['job', 'status'], name='scheduler_j_job_id_2b446a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerjobrecipient',
            index=models.Index(fields=['phone_number'], name='scheduler_j_phone_n_e4be03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schedulerjobrecipient',
            unique_together={('job', 'phone_number')},
        ),
    ]
