# Generated by Django 5.2.9 on 2026-01-03 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_datadeletionrequest_featureflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantKnowledgeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keywords', models.JSONField(help_text="List of keywords to match, e.g. ['fee', 'price', 'cost']")),
                ('english_response', models.TextField(help_text='Response in English')),
                ('marathi_response', models.TextField(blank=True, default='', help_text='Response in Marathi (optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Knowledge Entry',
                'verbose_name_plural': 'Knowledge Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
