# Generated by Django 6.0 on 2025-12-18 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, help_text='Commission percentage for billing', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'db_table': 'agencies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='active_users_limit',
            field=models.IntegerField(default=5, help_text='Maximum active users'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ai_features_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='api_rate_limit',
            field=models.IntegerField(default=60, help_text='API calls per minute'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(blank=True, choices=[('ECOMMERCE', 'E-Commerce'), ('SERVICE', 'Service'), ('SAAS', 'SaaS'), ('RETAIL', 'Retail'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='campaigns_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='monthly_message_limit',
            field=models.IntegerField(default=1000, help_text='Monthly message limit'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='webhooks_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='Business name', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='key_name',
            field=models.CharField(help_text='Key identifier: access_token, phone_number_id, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenants.agency'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Parent agency (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='tenants.agency'),
        ),
    ]
