# Generated by Antigravity - Data migration for webhook_token

import secrets
from django.db import migrations, models


def generate_webhook_tokens(apps, schema_editor):
    """Generate unique webhook tokens for all existing tenants."""
    Tenant = apps.get_model('tenants', 'Tenant')
    for tenant in Tenant.objects.all():
        if not tenant.webhook_token:
            tenant.webhook_token = secrets.token_urlsafe(32)
            tenant.save(update_fields=['webhook_token'])


def reverse_tokens(apps, schema_editor):
    """Reverse migration - clear tokens."""
    Tenant = apps.get_model('tenants', 'Tenant')
    Tenant.objects.all().update(webhook_token='')


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_datadeletionrequest_featureflag'),
    ]

    operations = [
        # First add field without unique constraint
        migrations.AddField(
            model_name='tenant',
            name='webhook_token',
            field=models.CharField(blank=True, default='', help_text='Auto-generated webhook verification token for Meta WhatsApp', max_length=64),
        ),
        # Populate existing records with unique tokens
        migrations.RunPython(generate_webhook_tokens, reverse_tokens),
        # Now add the unique constraint
        migrations.AlterField(
            model_name='tenant',
            name='webhook_token',
            field=models.CharField(blank=True, help_text='Auto-generated webhook verification token for Meta WhatsApp', max_length=64, unique=True),
        ),
    ]
