# Generated by Django 5.2.9 on 2026-01-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_webhook_token'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status'], name='tenants_status_80d9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['agency'], name='tenants_agency__1c6eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['created_at'], name='tenants_created_fc84fe_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['agency', 'status'], name='tenants_agency__a333b5_idx'),
        ),
    ]
