# Generated by Django 6.0 on 2025-12-18 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_agency_tenant_active_users_limit_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='For Agency Admins', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.agency'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('AGENCY_ADMIN', 'Agency Admin'), ('TENANT_ADMIN', 'Tenant Admin'), ('TENANT_USER', 'Tenant User')], default='TENANT_USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Null for Super Admins and Agency Admins', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant'),
        ),
    ]
