# Generated by Django 6.0 on 2025-12-20 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('messaging', '0001_initial'),
        ('tenants', '0004_datadeletionrequest_featureflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_sent', models.IntegerField(default=0)),
                ('delivered', models.IntegerField(default=0)),
                ('read', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('read_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Stats',
                'verbose_name_plural': 'Campaign Stats',
                'db_table': 'campaign_stats',
            },
        ),
        migrations.CreateModel(
            name='ClientQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_message_limit', models.IntegerField(default=100)),
                ('monthly_message_limit', models.IntegerField(default=1000)),
                ('messages_sent_today', models.IntegerField(default=0)),
                ('messages_sent_this_month', models.IntegerField(default=0)),
                ('last_daily_reset', models.DateField(blank=True, null=True)),
                ('last_monthly_reset', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Client Quota',
                'verbose_name_plural': 'Client Quotas',
                'db_table': 'client_quotas',
            },
        ),
        migrations.CreateModel(
            name='MessageAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_latency', models.IntegerField(blank=True, null=True)),
                ('read_latency', models.IntegerField(blank=True, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='messaging.message')),
            ],
            options={
                'verbose_name': 'Message Analytics',
                'verbose_name_plural': 'Message Analytics',
                'db_table': 'message_analytics',
            },
        ),
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('time_window', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit_logs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Rate Limit Log',
                'verbose_name_plural': 'Rate Limit Logs',
                'db_table': 'rate_limit_logs',
                'indexes': [models.Index(fields=['tenant', 'endpoint', 'time_window'], name='rate_limit__tenant__8ee879_idx')],
            },
        ),
    ]
