# Generated by Django 6.0 on 2025-12-20 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_datadeletionrequest_featureflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, help_text='WhatsApp phone number', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Contact name', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Contact tags for segmentation')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional contact data')),
                ('is_subscribed', models.BooleanField(default=True, help_text='Opted in to receive messages')),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Client this contact belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wa_conversation_id', models.CharField(blank=True, db_index=True, help_text='WhatsApp conversation ID', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='messaging.contact')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wa_message_id', models.CharField(blank=True, db_index=True, help_text='WhatsApp message ID from Meta', max_length=100)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=10)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('STICKER', 'Sticker'), ('LOCATION', 'Location'), ('CONTACTS', 'Contacts'), ('TEMPLATE', 'Template'), ('INTERACTIVE', 'Interactive'), ('REACTION', 'Reaction')], default='TEXT', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Text content of message')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Full message payload (media, template params, etc.)')),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_mime_type', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', '-created_at'], name='messages_convers_38b855_idx'), models.Index(fields=['wa_message_id'], name='messages_wa_mess_2dc395_idx')],
            },
        ),
    ]
