# Generated by Django 5.2.9 on 2025-12-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_contactimport_mediaasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactimport',
            name='name',
            field=models.CharField(blank=True, help_text='Custom name for this import', max_length=255),
        ),
    ]
