# Generated by Django 5.2.9 on 2026-01-31 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_contactimport_name'),
        ('tenants', '0006_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', '-created_at'], name='contacts_tenant__61cb55_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'is_subscribed'], name='contacts_tenant__2cf449_idx'),
        ),
        migrations.AddIndex(
            model_name='contactimport',
            index=models.Index(fields=['tenant', '-created_at'], name='contact_imp_tenant__2f8aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='contactimport',
            index=models.Index(fields=['tenant', 'status'], name='contact_imp_tenant__6c83cc_idx'),
        ),
    ]
