# Generated by Django 5.2.11 on 2026-03-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_add_import_source_to_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="content_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MIME type for serving",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="file_data",
            field=models.BinaryField(
                blank=True, help_text="File content stored in DB", null=True
            ),
        ),
    ]
