# Generated by Django 5.2.11 on 2026-03-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0006_add_file_data_to_media_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="public_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Random token required to access file without auth",
                max_length=64,
            ),
        ),
    ]
