# Generated by Django on 2025-12-27
# Initial migration for templates app

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(help_text='Unique template name', max_length=255)),
                ('header_image', models.ImageField(blank=True, help_text='Template header image for WhatsApp', null=True, upload_to='templates/headers/')),
                ('has_variables', models.BooleanField(default=False, help_text='Whether this template uses variables')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variables: [{"name": "username", "type": "text"}, ...]')),
                ('has_buttons', models.BooleanField(default=False, help_text='Whether this template has action buttons')),
                ('buttons', models.JSONField(blank=True, default=list, help_text='List of buttons: [{"text": "Visit", "type": "URL", "value": "https://..."}, ...]')),
                ('preview_image_with_vars', models.ImageField(blank=True, help_text='Preview showing template with sample variable data', null=True, upload_to='templates/previews/')),
                ('preview_image_without_vars', models.ImageField(blank=True, help_text='Preview showing template without variables', null=True, upload_to='templates/previews/')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_clients', models.ManyToManyField(blank=True, help_text='Clients that can use this template', related_name='whatsapp_templates', to='tenants.tenant')),
                ('created_by', models.ForeignKey(blank=True, help_text='SuperAdmin who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'db_table': 'whatsapp_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
