# Generated by Django 5.2.9 on 2025-12-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='header_media_image',
            field=models.ImageField(blank=True, help_text='Header image file', null=True, upload_to='templates/headers/images/'),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='header_media_type',
            field=models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video'), ('both', 'Both')], default='none', help_text='Type of header media: none, image, video, or both', max_length=10),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='header_media_video',
            field=models.FileField(blank=True, help_text='Header video file', null=True, upload_to='templates/headers/videos/'),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='language',
            field=models.CharField(default='en_US', help_text='Template language code (e.g. en_US, hi_IN, mr_IN)', max_length=10),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='template_id',
            field=models.CharField(default='default_template', help_text='Meta WhatsApp template ID', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Template header image for WhatsApp (legacy)', null=True, upload_to='templates/headers/'),
        ),
    ]
