# Generated by Django 5.2.9 on 2025-12-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_add_template_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='buttons_config',
            field=models.JSONField(blank=True, default=dict, help_text='Buttons config: {"enabled": bool, "buttons": [{"type": "URL|PHONE|QUICK_REPLY", "label": "", "value": ""}]}'),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='preview_assets',
            field=models.JSONField(blank=True, default=dict, help_text='Preview URLs: {"with_variables": "url", "without_variables": "url"}'),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='template_media',
            field=models.JSONField(blank=True, default=dict, help_text='Media config: {"enabled": bool, "allowed_types": ["image","video"], "multiple": bool}'),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='template_type',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utility'), ('authentication', 'Authentication')], default='marketing', help_text='Meta template type', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='variables_config',
            field=models.JSONField(blank=True, default=dict, help_text='Variables config: {"enabled": bool, "variable_type": "text|number|mixed", "variables": [...]}'),
        ),
    ]
