# Generated by Django 5.2.9 on 2026-01-31 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_add_universal_template_metadata'),
        ('tenants', '0006_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['created_at'], name='whatsapp_te_created_ca7962_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['is_active', 'created_at'], name='whatsapp_te_is_acti_af2aeb_idx'),
        ),
    ]
