# Generated by Django 5.2.11 on 2026-02-25 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_add_indexes'),
        ('tenants', '0006_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedMetaTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta_template_id', models.CharField(help_text='Meta Graph API template ID (numeric string)', max_length=100)),
                ('name', models.CharField(help_text='Template name', max_length=512)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled'), ('IN_APPEAL', 'In Appeal')], db_index=True, default='PENDING', max_length=20)),
                ('category', models.CharField(choices=[('UTILITY', 'Utility'), ('MARKETING', 'Marketing'), ('AUTHENTICATION', 'Authentication')], db_index=True, default='UTILITY', max_length=20)),
                ('language', models.CharField(db_index=True, default='en_US', max_length=20)),
                ('components', models.JSONField(blank=True, default=list)),
                ('quality_score', models.CharField(blank=True, default='', max_length=50)),
                ('rejected_reason', models.TextField(blank=True, default='')),
                ('industry', models.CharField(blank=True, db_index=True, default='', help_text='E-commerce, Financial Services, Telecommunication, Healthcare, etc.', max_length=100)),
                ('feature_group', models.CharField(blank=True, db_index=True, default='', help_text='Account Updates, Order Management, Payments, Event Reminder, etc.', max_length=100)),
                ('use_case', models.CharField(blank=True, db_index=True, default='', help_text='Delivery update, Payment reminder, Appointment confirmation, etc.', max_length=200)),
                ('has_header', models.BooleanField(default=False)),
                ('header_format', models.CharField(blank=True, default='', max_length=20)),
                ('has_buttons', models.BooleanField(default=False)),
                ('button_count', models.IntegerField(default=0)),
                ('body_text', models.TextField(blank=True, default='', help_text='Extracted body text for search')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(help_text='Tenant whose WABA this template was fetched from', on_delete=django.db.models.deletion.CASCADE, related_name='cached_meta_templates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Cached Meta Template',
                'verbose_name_plural': 'Cached Meta Templates',
                'db_table': 'cached_meta_templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='cached_mt_tenant_status_idx'), models.Index(fields=['tenant', 'category'], name='cached_mt_tenant_cat_idx'), models.Index(fields=['tenant', 'industry'], name='cached_mt_tenant_ind_idx'), models.Index(fields=['tenant', 'feature_group'], name='cached_mt_tenant_feat_idx'), models.Index(fields=['name'], name='cached_mt_name_idx')],
                'unique_together': {('tenant', 'meta_template_id', 'language')},
            },
        ),
    ]
