# Generated by Django 5.2.11 on 2026-02-28 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(help_text='Customer WhatsApp phone in E.164 format (e.g. +919876543210)', max_length=30)),
                ('customer_name', models.CharField(blank=True, default='', help_text='Resolved display name; updated from profile or contact book', max_length=255)),
                ('last_message', models.TextField(blank=True, default='', help_text='Preview text of the most recent message')),
                ('last_message_time', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the most recent message', null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_conversations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Inbox Conversation',
                'verbose_name_plural': 'Inbox Conversations',
                'db_table': 'inbox_conversations',
                'ordering': ['-last_message_time'],
            },
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta_message_id', models.CharField(blank=True, db_index=True, help_text='WhatsApp message ID from Meta Graph API', max_length=200)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], db_index=True, max_length=10)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('STICKER', 'Sticker'), ('LOCATION', 'Location'), ('CONTACTS', 'Contacts'), ('INTERACTIVE', 'Interactive'), ('REACTION', 'Reaction'), ('TEMPLATE', 'Template'), ('UNSUPPORTED', 'Unsupported')], default='TEXT', max_length=20)),
                ('content_json', models.JSONField(blank=True, default=dict, help_text='Full message payload as received from / sent to Meta')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('timestamp', models.BigIntegerField(blank=True, help_text='Epoch timestamp from Meta webhook payload', null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.inboxconversation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_messages', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Inbox Message',
                'verbose_name_plural': 'Inbox Messages',
                'db_table': 'inbox_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inboxconversation',
            index=models.Index(fields=['tenant', '-last_message_time'], name='idx_inbox_conv_tenant_time'),
        ),
        migrations.AddIndex(
            model_name='inboxconversation',
            index=models.Index(fields=['tenant', 'customer_phone'], name='idx_inbox_conv_tenant_phone'),
        ),
        migrations.AlterUniqueTogether(
            name='inboxconversation',
            unique_together={('tenant', 'customer_phone')},
        ),
        migrations.AddIndex(
            model_name='inboxmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='idx_inbox_msg_conv_created'),
        ),
        migrations.AddIndex(
            model_name='inboxmessage',
            index=models.Index(fields=['tenant', '-created_at'], name='idx_inbox_msg_tenant_created'),
        ),
        migrations.AddIndex(
            model_name='inboxmessage',
            index=models.Index(fields=['meta_message_id'], name='idx_inbox_msg_meta_id'),
        ),
    ]
