# Generated by Django 5.2.9 on 2026-01-31 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tenants', '0005_tenant_webhook_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Agency this notification belongs to (for agency-level notifications)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.agency'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this notification belongs to (for client-level notifications)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data: campaign_id, etc.'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['agency', 'is_read'], name='notif_agency_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'is_read'], name='notif_tenant_read_idx'),
        ),
    ]
