# Generated by Django 5.2.9 on 2026-01-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_agency_tenant_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notif_user_read_idx',
            old_name='notificatio_user_id_a4dd5c_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notif_user_created_idx',
            old_name='notificatio_user_id_7336fd_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notif_type_idx',
            old_name='notificatio_notific_19df93_idx',
        ),
    ]
