# Generated by Django 5.2.11 on 2026-02-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('CAMPAIGN_COMPLETED', 'Campaign Completed'), ('API_RATE_LIMIT', 'API Rate Limit Warning'), ('QUOTA_WARNING', 'Quota Warning'), ('STATUS_CHANGED', 'Status Changed'), ('PLAN_EXPIRING', 'Plan Expiring'), ('PAYMENT_FAILED', 'Payment Failed'), ('NEW_CLIENT', 'New Client Created'), ('NEW_AGENCY', 'New Agency Created'), ('SYSTEM_ERROR', 'System Error'), ('CAMPAIGN_FAILED', 'Campaign Failed'), ('API_ERROR', 'API Error'), ('SECURITY_ALERT', 'Security Alert')], db_index=True, max_length=50),
        ),
    ]
