# Generated by Django 6.0 on 2025-12-20 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        ('tenants', '0004_datadeletionrequest_featureflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template_name', models.CharField(blank=True, help_text='WhatsApp message template name', max_length=255)),
                ('template_params', models.JSONField(blank=True, default=list, help_text='Default template parameters')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When the campaign should start', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_tags', models.JSONField(blank=True, default=list, help_text='Contact tags to target')),
                ('target_all', models.BooleanField(default=False, help_text='Target all contacts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Client this campaign belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('custom_params', models.JSONField(blank=True, default=list, help_text='Contact-specific template params')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='messaging.contact')),
            ],
            options={
                'verbose_name': 'Scheduled Message',
                'verbose_name_plural': 'Scheduled Messages',
                'db_table': 'scheduled_messages',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, help_text='Actual message sent (if successful)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_results', to='messaging.message')),
                ('scheduled_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='campaigns.scheduledmessage')),
            ],
            options={
                'verbose_name': 'Message Result',
                'verbose_name_plural': 'Message Results',
                'db_table': 'message_results',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(fields=['status', 'scheduled_at'], name='scheduled_m_status_c4bde9_idx'),
        ),
    ]
