# Generated by Django 5.2.9 on 2025-12-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('promotional', 'Promotional'), ('reminder', 'Reminder'), ('follow_up', 'Follow-up')], default='announcement', help_text='Type of campaign', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Campaign end date', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='message_template',
            field=models.TextField(blank=True, help_text='Message template content'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Campaign start date', null=True),
        ),
    ]
