# Generated by Django 5.2.9 on 2026-01-31 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_campaign_type_campaign_end_date_and_more'),
        ('tenants', '0006_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', '-created_at'], name='campaigns_tenant__f1021b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'status'], name='campaigns_tenant__d8e2a0_idx'),
        ),
    ]
