# Generated by Django 5.2.9 on 2026-02-01 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_add_indexes'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('template_params', models.JSONField(blank=True, default=list)),
                ('content', models.TextField(blank=True, help_text='Custom message content')),
                ('scheduled_at', models.DateTimeField(help_text='When this message should be sent')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('contact_group_id', models.UUIDField(blank=True, null=True)),
                ('target_all', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_messages', to='campaigns.campaign')),
                ('scheduler_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_messages', to='scheduler.schedulerjob')),
            ],
            options={
                'verbose_name': 'Campaign Message',
                'verbose_name_plural': 'Campaign Messages',
                'db_table': 'campaign_messages',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaign_me_campaig_27bd4e_idx'), models.Index(fields=['scheduled_at', 'status'], name='campaign_me_schedul_43d3ab_idx')],
            },
        ),
    ]
