# Generated by Django 5.2.11 on 2026-02-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaignmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmessage',
            name='cards_json',
            field=models.JSONField(blank=True, help_text='Carousel cards: [{"header": {...}, "bodyParams": [...], "buttonParams": []}]', null=True),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='header_data',
            field=models.JSONField(blank=True, help_text='Header media: {"type": "image"|"video", "url": "..."}', null=True),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='template_type',
            field=models.CharField(blank=True, default='standard', help_text='standard or carousel', max_length=20),
        ),
    ]
